#PostgreSQL
spring.datasource.url=jdbc:postgresql://node128.codingbc.com:7878/niv_test?
spring.datasource.username=postgres
spring.datasource.password=Nov2017890#
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

logging.level.org.hibernate.tool.schema.internal.ExceptionHandlerLoggedImpl=ERROR
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=ERROR


#Show me the money (show SQL command and format them)
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


#How we will work
spring.profiles.active=development


#To use spring swagger web
spring.mvc.pathmatch.matching-strategy=ant-path-matcher

# Increase validation timeout to reduce warnings on local dev machines
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-timeout=30000

